# Generated by Django 2.1.5 on 2019-10-26 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='University_Name',
        ),
        migrations.AddField(
            model_name='profile',
            name='university',
            field=models.CharField(default=None, max_length=40),
        ),
    ]
