# Generated by Django 2.1.5 on 2019-10-26 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20191026_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ranking',
        ),
    ]
