# Generated by Django 2.1.5 on 2019-10-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_profile_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ranking',
            field=models.CharField(default='member', max_length=20),
        ),
    ]
