# Generated by Django 2.1.5 on 2019-10-27 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_profile_ranking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='ranking',
            field=models.CharField(default='member', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='total_dollars_raised',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='total_service_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='university',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
