# Generated by Django 2.1.5 on 2019-10-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20191026_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='club_chapter',
            fields=[
                ('club_id', models.IntegerField(primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=4)),
            ],
        ),
    ]
