# Generated by Django 2.1.5 on 2019-10-27 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_club_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='club_chapter',
            name='donations_raised',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='club_chapter',
            name='service_hours',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='club_chapter',
            name='total_members',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.club_chapter'),
        ),
    ]
