# Generated by Django 2.1.5 on 2019-11-01 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_auto_20191031_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club_chapter',
            name='donations_raised',
        ),
        migrations.RemoveField(
            model_name='club_chapter',
            name='service_hours',
        ),
        migrations.RemoveField(
            model_name='club_chapter',
            name='total_members',
        ),
        migrations.AddField(
            model_name='work_order',
            name='club_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='catalog.Club_Chapter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service_project',
            name='club_chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.Club_Chapter'),
        ),
        migrations.AlterField(
            model_name='user',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.Club_Chapter'),
        ),
    ]
