# Generated by Django 2.1.5 on 2019-11-05 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0041_auto_20191104_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_registered', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Worker for project',
                'verbose_name_plural': 'Workers for projects',
                'ordering': ['time_registered'],
            },
        ),
        migrations.AlterField(
            model_name='service_project',
            name='club_chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.Club_Chapter'),
        ),
        migrations.AlterField(
            model_name='user',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.Club_Chapter'),
        ),
        migrations.AlterField(
            model_name='user',
            name='working',
            field=models.ManyToManyField(to='catalog.Service_Project'),
        ),
        migrations.AddField(
            model_name='projectregistration',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.Service_Project', verbose_name='Project'),
        ),
        migrations.AddField(
            model_name='projectregistration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Worker'),
        ),
        migrations.AlterUniqueTogether(
            name='projectregistration',
            unique_together={('user', 'project')},
        ),
    ]
