# Generated by Django 2.1.5 on 2019-11-14 02:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0074_auto_20191112_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_project',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='service_project',
            name='project_date',
        ),
        migrations.RemoveField(
            model_name='service_project',
            name='start_time',
        ),
        migrations.AddField(
            model_name='service_project',
            name='project_date_end',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Enter field documentation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service_project',
            name='project_date_start',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Enter field documentation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectregistration',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.Service_Project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='service_project',
            name='club_chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.Club_Chapter'),
        ),
        migrations.AlterField(
            model_name='user',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.Club_Chapter'),
        ),
    ]
