# Generated by Django 2.1.5 on 2019-11-18 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0083_auto_20191115_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_donated', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.Club_Chapter', verbose_name='Donation')),
            ],
        ),
        migrations.CreateModel(
            name='Donation_Drive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Enter field documentation', max_length=200)),
                ('goal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('datetime_start', models.DateTimeField(help_text='Enter field documentation')),
                ('datetime_end', models.DateTimeField(help_text='Enter field documentation')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Club_Chapter', verbose_name='Club')),
            ],
        ),
        migrations.AlterField(
            model_name='projectregistration',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Club_Chapter', verbose_name='Club'),
        ),
        migrations.AlterField(
            model_name='projectregistration',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.Service_Project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='service_project',
            name='club_chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.Club_Chapter'),
        ),
        migrations.AlterField(
            model_name='user',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.Club_Chapter'),
        ),
        migrations.AddField(
            model_name='donation',
            name='drive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.Donation_Drive', verbose_name='Drive'),
        ),
        migrations.AddField(
            model_name='donation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Worker'),
        ),
    ]
