#Generated by Django 2.1.5 on 2019-10-04 01:37


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='weekly_projects',
            fields=[
                ('project_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('project_title', models.CharField(help_text='Enter field documentation', max_length=15)),
                ('project_duration', models.CharField(help_text='Enter field documentation', max_length=15)),
                ('location', models.CharField(help_text='Enter field documentation', max_length=15)),
                ('project_leader', models.CharField(help_text='Enter field documentation', max_length=15)),
                ('week_date', models.CharField(help_text='Enter field documentation', max_length=15)),
            ],
        ),
    ]
